.TH "Referencia del directorio srclib" 3 "Lunes, 7 de Marzo de 2016" "Practica 1 - Redes de Comunicaciones II" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Referencia del directorio srclib \- 
.SH SYNOPSIS
.br
.PP
.SS "Archivos"

.in +1c
.ti -1c
.RI "archivo \fBG-2301-01-P1-daemon\&.c\fP"
.br
.RI "\fILibreria de creacion de un daemon\&. \fP"
.ti -1c
.RI "archivo \fBG-2301-01-P1-irc\&.c\fP"
.br
.RI "\fILibreria de manejo de mensajes IRC\&. \fP"
.ti -1c
.RI "archivo \fBG-2301-01-P1-server\&.c\fP"
.br
.RI "\fILibreria de manejo de un servidor de sockets\&. \fP"
.ti -1c
.RI "archivo \fBG-2301-01-P1-tcp\&.c\fP"
.br
.RI "\fILibreria de manejo de sockets TCP\&. \fP"
.ti -1c
.RI "archivo \fBG-2301-01-P1-tools\&.c\fP"
.br
.RI "\fILibreria de utilidades\&. \fP"
.ti -1c
.RI "archivo \fBG-2301-01-P1-udp\&.c\fP"
.br
.in -1c
