.TH "Referencia del directorio src" 3 "Domingo, 6 de Marzo de 2016" "Practica 1 - Redes de Comunicaciones II" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Referencia del directorio src \- 
.SH SYNOPSIS
.br
.PP
.SS "Archivos"

.in +1c
.ti -1c
.RI "archivo \fBclient\&.c\fP"
.br
.ti -1c
.RI "archivo \fBecho-server\&.c\fP"
.br
.ti -1c
.RI "archivo \fBG-2301-01-P1-client\&.c\fP"
.br
.ti -1c
.RI "archivo \fBG-2301-01-P1-echo_server\&.c\fP"
.br
.ti -1c
.RI "archivo \fBG-2301-01-P1-irc_server\&.c\fP"
.br
.in -1c
